# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

variables:
  JAVA_HOME: 'C:\Program Files\Java\jdk-23'
  MAVEN_HOME: 'C:\Program Files\Apache\maven\apache-maven-3.9.9'

pool: bagent1

steps:
- script: |
    echo Adding Maven to PATH
    set PATH=C:\Program Files\Apache\maven\apache-maven-3.9.9\bin;%PATH%
  displayName: 'Add Maven to PATH'
  
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '23'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'



