# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool: bagent1

steps:
- task: Maven@4
  inputs:
    mavenVersionSelection: 'Path'
    mavenPath: 'C:\\Program Files\\Apache\\maven\\apache-maven-3.9.9'
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: Path
    jdkDirectory: 'C:\\Program Files\\Java\\jdk-18.0.2.1'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
  




